sudo: required
services: 
    - docker

before_install: 
    - docker build -t jordanfrontdev/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jordanfrontdev/react-test npm run test   

after_success: 
    - docker build -t jordanfrontdev/multi-client ./client
    - docker build -t jordanfrontdev/multi-nginx ./nginx
    - docker build -t jordanfrontdev/multi-server ./server
    - docker build -t jordanfrontdev/multi-worker ./worker
    # log in to docker CLI with travis environment variables
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push jordanfrontdev/multi-client
    - docker push jordanfrontdev/multi-nginx
    - docker push jordanfrontdev/multi-server
    - docker push jordanfrontdev/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: Multidocker-env
    bucket_name: elasticbeanstalk-us-east-2-211326317533
    bucket_path: docker-multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY


